[
   {
      "id":"447bf0553688cb25",
      "type":"server-state-changed",
      "z":"1f61e07f53956bdf",
      "name":"Tent Rh Change",
      "server":"",
      "version":4,
      "exposeToHomeAssistant":false,
      "haConfig":[
         {
            "property":"name",
            "value":""
         },
         {
            "property":"icon",
            "value":""
         }
      ],
      "entityidfilter":"sensor.tent_rh_and_temp_humidity",
      "entityidfiltertype":"exact",
      "outputinitially":false,
      "state_type":"str",
      "haltifstate":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "outputs":1,
      "output_only_on_state_change":true,
      "for":"0",
      "forType":"num",
      "forUnits":"minutes",
      "ignorePrevStateNull":false,
      "ignorePrevStateUnknown":false,
      "ignorePrevStateUnavailable":false,
      "ignoreCurrentStateUnknown":false,
      "ignoreCurrentStateUnavailable":false,
      "outputProperties":[
         {
            "property":"payload",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"eventData"
         },
         {
            "property":"topic",
            "propertyType":"msg",
            "value":"",
            "valueType":"triggerId"
         }
      ],
      "x":100,
      "y":180,
      "wires":[
         [
            "7f126de5e326f770"
         ]
      ]
   },
   {
      "id":"7f126de5e326f770",
      "type":"api-current-state",
      "z":"1f61e07f53956bdf",
      "name":"Brightness",
      "server":"",
      "version":3,
      "outputs":1,
      "halt_if":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "entity_id":"light.inline_fan_controller_dimmer",
      "state_type":"str",
      "blockInputOverrides":false,
      "outputProperties":[
         {
            "property":"payload",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"entity"
         },
         {
            "property":"brightness",
            "propertyType":"msg",
            "value":"data.attributes.brightness",
            "valueType":"jsonata"
         }
      ],
      "for":"0",
      "forType":"num",
      "forUnits":"minutes",
      "override_topic":false,
      "state_location":"payload",
      "override_payload":"msg",
      "entity_location":"data",
      "override_data":"msg",
      "x":310,
      "y":200,
      "wires":[
         [
            "e38e3d413ca473cd"
         ]
      ]
   },
   {
      "id":"38939c2b8291c016",
      "type":"server-state-changed",
      "z":"1f61e07f53956bdf",
      "name":"Tent temp Change",
      "server":"",
      "version":4,
      "exposeToHomeAssistant":false,
      "haConfig":[
         {
            "property":"name",
            "value":""
         },
         {
            "property":"icon",
            "value":""
         }
      ],
      "entityidfilter":"sensor.tent_rh_and_temp_temperature",
      "entityidfiltertype":"exact",
      "outputinitially":false,
      "state_type":"str",
      "haltifstate":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "outputs":1,
      "output_only_on_state_change":true,
      "for":"0",
      "forType":"num",
      "forUnits":"minutes",
      "ignorePrevStateNull":false,
      "ignorePrevStateUnknown":false,
      "ignorePrevStateUnavailable":false,
      "ignoreCurrentStateUnknown":false,
      "ignoreCurrentStateUnavailable":false,
      "outputProperties":[
         {
            "property":"payload",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"eventData"
         },
         {
            "property":"topic",
            "propertyType":"msg",
            "value":"",
            "valueType":"triggerId"
         }
      ],
      "x":110,
      "y":240,
      "wires":[
         [
            "7f126de5e326f770"
         ]
      ]
   },
   {
      "id":"e38e3d413ca473cd",
      "type":"api-current-state",
      "z":"1f61e07f53956bdf",
      "name":"Get current Rh",
      "server":"",
      "version":3,
      "outputs":1,
      "halt_if":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "entity_id":"sensor.tent_rh_and_temp_humidity",
      "state_type":"num",
      "blockInputOverrides":false,
      "outputProperties":[
         {
            "property":"rh",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"entity"
         },
         {
            "property":"temp",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         }
      ],
      "for":0,
      "forType":"num",
      "forUnits":"minutes",
      "x":480,
      "y":200,
      "wires":[
         [
            "fdb815399a1e7da2"
         ]
      ]
   },
   {
      "id":"fdb815399a1e7da2",
      "type":"api-current-state",
      "z":"1f61e07f53956bdf",
      "name":"get req rh",
      "server":"",
      "version":3,
      "outputs":1,
      "halt_if":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "entity_id":"sensor.required_rh_kpa_vpd_tent",
      "state_type":"num",
      "blockInputOverrides":false,
      "outputProperties":[
         {
            "property":"req_rh",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"entity"
         }
      ],
      "for":"0",
      "forType":"num",
      "forUnits":"minutes",
      "override_topic":false,
      "state_location":"payload",
      "override_payload":"msg",
      "entity_location":"data",
      "override_data":"msg",
      "x":620,
      "y":260,
      "wires":[
         [
            "3d88322a6d31859f"
         ]
      ]
   },
   {
      "id":"3d88322a6d31859f",
      "type":"api-current-state",
      "z":"1f61e07f53956bdf",
      "name":"tent temperature",
      "server":"",
      "version":3,
      "outputs":1,
      "halt_if":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "entity_id":"sensor.tent_rh_and_temp_temperature",
      "state_type":"num",
      "blockInputOverrides":false,
      "outputProperties":[
         {
            "property":"payload",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"entity"
         },
         {
            "property":"temp",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         }
      ],
      "for":0,
      "forType":"num",
      "forUnits":"minutes",
      "x":780,
      "y":260,
      "wires":[
         [
            "b25e959903f0b980"
         ]
      ]
   },
   {
      "id":"b25e959903f0b980",
      "type":"api-current-state",
      "z":"1f61e07f53956bdf",
      "name":"desired temperature",
      "server":"",
      "version":3,
      "outputs":1,
      "halt_if":"",
      "halt_if_type":"str",
      "halt_if_compare":"is",
      "entity_id":"input_number.desired_tent_temp",
      "state_type":"num",
      "blockInputOverrides":false,
      "outputProperties":[
         {
            "property":"desiredTemperature",
            "propertyType":"msg",
            "value":"",
            "valueType":"entityState"
         },
         {
            "property":"data",
            "propertyType":"msg",
            "value":"",
            "valueType":"entity"
         }
      ],
      "for":0,
      "forType":"num",
      "forUnits":"minutes",
      "x":980,
      "y":260,
      "wires":[
         [
            "9ded306469c47ea5"
         ]
      ]
   },
   {
      "id":"9ded306469c47ea5",
      "type":"function",
      "z":"1f61e07f53956bdf",
      "name":"Set Fan Speed Based on temp and current speed",
      "func":"const currentRh = msg.rh;\nconst requiredRh = msg.req_rh;\nconst currentTemp = msg.temp;\nconst desiredTemp = msg.desiredTemperature;\nconst currentBrightness = msg.brightness;\nconst maxBrightness = 105;\nconst minBrightness = 0;\nconst brightnessScaling = 5; // Set the brightness scaling to a static value of 5\n\n//console.log(currentRh, requiredRh)\n//get temp defference\nlet tempDifference = currentTemp - desiredTemp;\nlet rhDifference = currentRh - requiredRh;\n//console.log(tempDifference, rhDifference)\n\nif (rhDifference <= 0 && tempDifference <= 0) {\n    msg.brightness = 1;\n    msg.payload = msg.brightness;\n    return msg;\n} else {\n    msg.brightness = Math.min(msg.brightness + brightnessScaling, maxBrightness);\n    msg.payload = msg.brightness;\n    return msg;\n}",
      "outputs":1,
      "noerr":0,
      "initialize":"",
      "finalize":"",
      "libs":[
         
      ],
      "x":1290,
      "y":260,
      "wires":[
         [
            "e8648b1332084d7b",
            "31dc3b1c9655b0d3"
         ]
      ]
   },
   {
      "id":"e8648b1332084d7b",
      "type":"debug",
      "z":"1f61e07f53956bdf",
      "name":"debug 2",
      "active":true,
      "tosidebar":true,
      "console":false,
      "tostatus":false,
      "complete":"true",
      "targetType":"full",
      "statusVal":"",
      "statusType":"auto",
      "x":1280,
      "y":340,
      "wires":[
         
      ]
   },
   {
      "id":"31dc3b1c9655b0d3",
      "type":"api-call-service",
      "z":"1f61e07f53956bdf",
      "name":"",
      "server":"",
      "version":5,
      "debugenabled":false,
      "domain":"light",
      "service":"turn_on",
      "areaId":[
         
      ],
      "deviceId":[
         
      ],
      "entityId":[
         "light.inline_fan_controller_dimmer"
      ],
      "data":"{\"brightness\":msg.payload}",
      "dataType":"jsonata",
      "mergeContext":"",
      "mustacheAltTags":false,
      "outputProperties":[
         
      ],
      "queue":"none",
      "x":1610,
      "y":260,
      "wires":[
         [
            
         ]
      ]
   }
]
